export const styles: Record<string, React.CSSProperties> = {
    container: {
      display: "flex",
      flexDirection: "row" as const,
      height: "85vh",
      position: "absolute" as const,
    },
    tariffPanel: {
      display: "flex",
      flexDirection: "column",
      flex: 1,
      overflow: "hidden",
      maxWidth: "650px",
      width: "650px",
      margin: "0 auto",
      color: "white",
      marginLeft: 20,
      zIndex: 1,
      height: "100%",
      backgroundColor: "rgba(0, 0, 0, 0.53)",
      borderRadius: "8px",
      boxShadow: "0 4px 30px rgba(0, 0, 0, 0.1)",
      backdropFilter: "blur(9.7px)",
      WebkitBackdropFilter: "blur(9.7px)",
      border: "1px solid rgba(255, 255, 255, 0.3)",
    },
    modalContent: {
      overflowY: "auto",
      padding: "10px",
    },
    modalActions: {
      display: "flex",
      justifyContent: "flex-end",
      gap: "10px",
      marginTop: "20px",
      paddingTop: "15px",
      borderTop: "1px solid rgba(255, 255, 255, 0.2)",
      flex: "0 0 auto",
      width: "100%",
    },
    formGroup: {
      marginBottom: "20px",
      width: "100%",
    },
    formLabel: {
      fontWeight: "500",
      display: "block",
      marginBottom: "8px",
      color: "white",
    },
    sectionHeader: {
      margin: "15px 0 10px 0",
      color: "white",
      fontSize: "16px",
      fontWeight: "600",
    },
    timeGrid: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr",
      gap: "15px",
      marginTop: "10px",
      width: "100%",
    },
    timeSlotContainer: {
      display: "flex",
      flexDirection: "column",
      gap: "15px",
      marginTop: "10px",
      width: "100%",
    },
    timeSlot: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr auto",
      gap: "10px",
      alignItems: "end",
      width: "100%",
    },
    addTimeSlotButton: {
      marginTop: "10px",
      backgroundColor: "rgba(255, 255, 255, 0.1)",
      border: "1px dashed rgba(255, 255, 255, 0.3)",
      borderRadius: "4px",
      padding: "8px",
      width: "100%",
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      color: "white",
    },
    removeButton: {
      background: "none",
      border: "none",
      color: "#ff6b6b",
      cursor: "pointer",
      fontSize: "16px",
      padding: "4px 8px",
      borderRadius: "4px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    daySelector: {
      marginTop: "10px",
      display: "flex",
      gap: "10px",
      alignItems: "center",
      flexWrap: "wrap",
      width: "100%",
    },
    quickSelectButtons: {
      display: "flex",
      gap: "8px",
      marginTop: "8px",
      flexWrap: "wrap",
      width: "100%",
    },
    feeInput: {
      display: "flex",
      alignItems: "center",
      gap: "5px",
    },
    dropdownWrapper: {
      marginBottom: "20px",
      width: "100%",
    },
    tiersContainer: {
      marginTop: "15px",
      border: "1px solid rgba(255, 255, 255, 0.2)",
      borderRadius: "6px",
      padding: "10px",
    },
    tierHeader: {
      display: "grid",
      gridTemplateColumns: "40px 1fr 1fr 1fr 40px",
      gap: "10px",
      fontWeight: "bold",
      borderBottom: "1px solid rgba(255, 255, 255, 0.2)",
      paddingBottom: "8px",
      marginBottom: "8px",
      color: "white",
      width: "100%",
    },
    tierRow: {
      display: "grid",
      gridTemplateColumns: "40px 1fr 1fr 1fr 40px",
      gap: "10px",
      alignItems: "center",
      padding: "8px 0",
      borderBottom: "1px solid rgba(255, 255, 255, 0.1)",
      color: "white",
      width: "100%",
    },
    addTierButton: {
      marginTop: "10px",
      backgroundColor: "rgba(255, 255, 255, 0.1)",
      border: "1px dashed rgba(255, 255, 255, 0.3)",
      borderRadius: "4px",
      padding: "8px",
      width: "100%",
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      color: "white",
    },
    tierInput: {
      padding: "6px 8px",
      borderRadius: "4px",
      border: "1px solid rgba(255, 255, 255, 0.3)",
      backgroundColor: "rgba(255, 255, 255, 0.1)",
      color: "white",
      fontSize: "14px",
    },
    deleteButton: {
      background: "none",
      border: "none",
      color: "#ff6b6b",
      cursor: "pointer",
      fontSize: "16px",
      padding: "4px 8px",
      borderRadius: "4px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    input: {
      width: "100%",
      padding: "8px 12px",
      borderRadius: "4px",
      border: "1px solid rgba(255, 255, 255, 0.3)",
      backgroundColor: "rgba(255, 255, 255, 0.1)",
      color: "white",
      fontSize: "14px",
      boxSizing: "border-box",
    },
    inputDisabled: {
      width: "100%",
      padding: "8px 12px",
      borderRadius: "4px",
      border: "1px solid rgba(255, 255, 255, 0.2)",
      backgroundColor: "rgba(255, 255, 255, 0.05)",
      color: "rgba(255, 255, 255, 0.6)",
      fontSize: "14px",
      boxSizing: "border-box",
      cursor: "not-allowed",
    },
    select: {
      width: "100%",
      padding: "8px 12px",
      borderRadius: "4px",
      border: "1px solid rgba(255, 255, 255, 0.3)",
      backgroundColor: "rgba(255, 255, 255, 0.1)",
      color: "white",
      fontSize: "14px",
      height: "36px",
      boxSizing: "border-box",
    },
    option: {
      backgroundColor: "rgba(45, 45, 45, 0.9)",
      color: "white",
    },
    helpText: {
      color: "rgba(255, 255, 255, 0.7)",
      fontSize: "12px",
      marginTop: "4px",
    },
    customButton: {
      backgroundColor: "rgba(255, 255, 255, 0.1)",
      color: "white",
      border: "1px solid rgba(255, 255, 255, 0.3)",
      borderRadius: "4px",
      padding: "8px 16px",
      cursor: "pointer",
      fontSize: "14px",
      transition: "all 0.2s ease",
    },
    customButtonDisabled: {
      backgroundColor: "rgba(255, 255, 255, 0.05)",
      color: "rgba(255, 255, 255, 0.4)",
      border: "1px solid rgba(255, 255, 255, 0.2)",
      borderRadius: "4px",
      padding: "8px 16px",
      cursor: "not-allowed",
      fontSize: "14px",
      transition: "all 0.2s ease",
    },
    primaryButton: {
      backgroundColor: "#10b981",
      color: "white",
      border: "none",
      borderRadius: "4px",
      padding: "8px 16px",
      cursor: "pointer",
      fontSize: "14px",
      fontWeight: 500,
      transition: "all 0.2s ease",
    },
    primaryButtonDisabled: {
      backgroundColor: "rgba(16, 185, 129, 0.3)",
      color: "rgba(255, 255, 255, 0.5)",
      border: "none",
      borderRadius: "4px",
      padding: "8px 16px",
      cursor: "not-allowed",
      fontSize: "14px",
      fontWeight: 500,
      transition: "all 0.2s ease",
    },
    buttonWrapper: {
      display: "inline-block",
      margin: "0 4px",
    },
    rateTypeToggle: {
      display: "flex",
      borderRadius: "4px",
      overflow: "hidden",
      width: "fit-content",
      border: "1px solid rgba(255, 255, 255, 0.2)",
    },
    rateTypeButtonActive: {
      padding: "8px 16px",
      border: "none",
      cursor: "pointer",
      transition: "all 0.2s ease",
      fontSize: "14px",
      fontWeight: 500,
      backgroundColor: "#10b981",
      color: "white",
    },
    rateTypeButtonInactive: {
      padding: "8px 16px",
      border: "none",
      cursor: "pointer",
      transition: "all 0.2s ease",
      fontSize: "14px",
      fontWeight: 500,
      background: "transparent",
      color: "white",
    },
    tierGrid: {
      display: "grid",
      gridTemplateColumns: "1fr 1fr 1fr 1fr",
      gap: "15px",
      marginTop: "10px",
      width: "100%",
    },
    closeButton: {
      background: "none",
      border: "none",
      color: "white",
      fontSize: "20px",
      cursor: "pointer",
      position: "absolute" as const,
      right: "20px",
      top: "50%",
      transform: "translateY(-50%)",
    },
    modalHeader: {
      display: "flex",
      padding: "15px 15px",
      borderBottom: "1px solid rgba(255, 255, 255, 0.2)",
      position: "relative" as const,
      zIndex: 1,
    },
  };
  
  export const stringStyles = {
    customScrollbarStyles: `
      .tariff-list::-webkit-scrollbar {
        width: 4px;
      }
      
      .tariff-list::-webkit-scrollbar-track {
        background: #3a3a3a;
        border-radius: 4px;
      }
      
      .tariff-list::-webkit-scrollbar-thumb {
        background: rgba(233, 233, 233, 0.5);
        border-radius: 4px;
        width: 8px;
      }
  
      .tariff-list::-webkit-scrollbar-thumb:hover {
        background: rgba(233, 233, 233, 0.8);
      }
    `,
  };